export const userConstants = {

    SET_FIRST_NAME: 'SET_FIRST_NAME',
    SET_LAST_NAME: 'SET_LAST_NAME',
    SET_USERNAME: 'SET_USERNAME',
    SET_EMAIL: 'SET_EMAIL',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_PASSWORD_CONFIRMATION: 'SET_PASSWORD_CONFIRMATION',

    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOG_IN: 'LOG_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',

    SIGN_OUT: 'SIGN_OUT',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    BLOCK_USER: 'BLOCK_USER',
    BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
    BLOCK_USER_FAILURE: 'BLOCK_USER_FAILURE',

    UNBLOCK_USER: 'UNBLOCK_USER',
    UNBLOCK_USER_SUCCESS: 'UNBLOCK_USER_SUCCESS',
    UNBLOCK_USER_FAILURE: 'UNBLOCK_USER_FAILURE',

    GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
    GET_BLOCKED_USERS_SUCCESS: 'GET_BLOCKED_USERS_SUCCESS',
    GET_BLOCKED_USERS_FAILURE: 'GET_BLOCKED_USERS_FAILURE',

    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    GET_CURRENT_PROFILE: 'GET_CURRENT_PROFILE',
    SET_CURRENT_USER_LOGIN: 'SET_CURRENT_USER_LOGIN',
    SET_CURRENT_USER_PASSWORD: 'SET_CURRENT_USER_PASSWORD',

    GET_INFO: 'GET_INFO',
    RESET: 'RESET'
}