export const blockUsersActionTypes = {

  BLOCK_USER: 'BLOCK_USER',
  BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
  BLOCK_USER_FAILURE: 'BLOCK_USER_FAILURE',

  UNBLOCK_USER: 'UNBLOCK_USER',
  UNBLOCK_USER_SUCCESS: 'UNBLOCK_USER_SUCCESS',
  UNBLOCK_USER_FAILURE: 'UNBLOCK_USER_FAILURE',

  GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
  GET_BLOCKED_USERS_SUCCESS: 'GET_BLOCKED_USERS_SUCCESS',
  GET_BLOCKED_USERS_FAILURE: 'GET_BLOCKED_USERS_FAILURE'
  
}  