export  const actionTypes = {
  CHANGE_CITY: "CHANGE_CITY",
  CHANGE_SUCCESSFULLY1: "CHANGE_SUCCESSFULLY1",
  CHANGE_FAILURE1: "CHANGE_FAILURE1",
  CHANGE_SUCCESSFULLY5: "CHANGE_SUCCESSFULLY5",
  CHANGE_FAILURE5: "CHANGE_FAILURE5",
  CHOOSE_FORECAST_TYPE: "CHOOSE_FORECAST_TYPE",
  CHOOSE_5_DAYS_FORECAST: "CHOOSE_5_DAYS_FORECAST"
};